### ISSUE TITLE
Unable to broadcast message using BLE

### ISSUE THREAD

**Issue by Harikrishnan-Selvaraj** [01org/corelibs-arduino101#169]
Am using Arduino-101 and I'm trying to broadcast my messages through BLE. Is there any possible way to broadcast the message without pairing or connecting to central device, so that all available devices can receive my message?

**Comment by eriknyquist** [comment]
Hi @Harikrishnan-Selvaraj , if you have question about how to use the API please direct them to the forum https://forum.arduino.cc/index.php?board=103. If you have found a bug, or you believe that a new feature is needed, please provide specific details about the bug or the feature so that we can help you more effectively.
