### ISSUE TITLE
error: #error "This library only supports boards with an AVR, SAM, SAMD, NRF52 or STM32F4 processor."  #error "This library only supports boards with an AVR, SAM, SAMD, NRF52 or STM32F4 processor."

### ISSUE THREAD

**Issue by ghost** [01org/corelibs-arduino101#605]
I am trying to use servo motor with ESP32 but it shows this error can anyone help me with it? i tried installing multiple libraries but still same issue

**Comment by gammmagna** [comment]
_### this type errror we are having caN YOU SLOVE_ WARNING: library Servo claims to run on avr, megaavr, sam, samd, nrf52, stm32f4, mbed, mbed_nano, mbed_portenta, mbed_rp2040, renesas, renesas_portenta, renesas_uno architecture(s) and may be incompatible with your current board which runs on esp32 architecture(s).
In file included from C:\Users\91767\AppData\Local\Temp\.arduinoIDE-unsaved2023113-9464-1r8poat.6e85\sketch_dec3a\sketch_dec3a.ino:9:
c:\Users\91767\Documents\Arduino\libraries\Servo\src/Servo.h:79:2: error: #error "This library only supports boards with an AVR, SAM, SAMD, NRF52 or STM32F4 processor."
 #error "This library only supports boards with an AVR, SAM, SAMD, NRF52 or STM32F4 processor."
  ^~~~~

exit status 1

Compilation error: exit status 1

**Comment by per1234** [comment]
@rohithmanivarma123 @gammmagna this is the repository for the platform of the [**Arduino 101**](https://docs.arduino.cc/retired/boards/arduino-101-619) board. I see you are using an ESP32 board instead of an **Arduino 101** so your problem is completely off topic here.

If you would like assistance with solving the problem you are experiencing, please post over on the Arduino forum:

https://forum.arduino.cc/c/using-arduino/programming-questions/20

We will definitely be able to help you over there.

@rohithmanivarma123 please close this off topic issue since it is not appropriate for this repository.
